import DropdownMenu from "@/components/DropdownMenu";
import Head from "next/head";
import {
  JSXElementConstructor,
  ReactElement,
  ReactFragment,
  useState,
} from "react";
import { motion } from "framer-motion";
import TopicPrompts from "@/components/TopicPrompts";
import CharacterSelect from "@/components/CharacterSelect";

const titles = {
  visible: { y: 0 },
  hidden: { y: "-200%" },
};

const startBtn = {
  visible: { bottom: 0 },
  hidden: { bottom: -200 },
};

const fadeOut = {
  visible: { opacity: 1 },
  hidden: { opacity: 0 },
};

export default function Home() {
  const [rapper1, setRapper1] = useState<string>("");
  const [rapper2, setRapper2] = useState<string>("");
  const [gameActive, setGameActive] = useState<boolean>(false);
  const [p1Turn, setP1Turn] = useState<boolean>(true);
  const [rapping, setRapping] = useState<boolean>(false);
  const verses: string[] = [];
  const [currentVerse, setCurrentVerse] = useState<string>("");

  const startGame = (e: any) => {
    console.log(rapper1);
    console.log(rapper2);
    setGameActive(true);
  };

  const startVerse = (topic: string) => {
    // calls API endpoint with the current rapper & topic, and returns a verse and the audio
    setCurrentVerse(
      `You are so ugly and dumb and stupid (yuh) you should probably eat some weiners, the topic is ${topic}`
    );
    setRapping(true);
  };

  return (
    <>
      <Head>
        <title>Co:here to Rule the Mic!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <div className="w-screen h-screen fixed bg-pixelart flex flex-col items-center">
          <div className="w-full h-full bg-black opacity-80 fixed -z-10"></div>
          <motion.div
            animate={gameActive ? "hidden" : "closed"}
            variants={titles}
            transition={{ ease: "circIn", duration: 1 }}
            className="flex flex-col justify-center items-center"
          >
            <h1 className="text-white text-4xl mt-12 text-center mx-4">
              Co:here to Rule the Mic!
            </h1>
            <p className="text-white text-sm mt-8 mx-4 max-w-sm">
              Listen up! It's the AI Rap Battle, two digital MCs clashin'
              rhymes, algorithms and beats, in a virtual arena, no human needed.
              They'll bring the heat and show what's possible, with bars so fly
              it'll leave you speechless. Get ready for a digital showdown, it's
              the AI Rap Battle, and it's gonna be lit!
            </p>
            <p className="text-yellow-100 mt-8 text-xl text-center">
              Choose your Rappers!
            </p>
          </motion.div>

          <CharacterSelect
            rapper1={rapper1}
            setRapper1={setRapper1}
            rapper2={rapper2}
            setRapper2={setRapper2}
            gameActive={gameActive}
            p1Turn={p1Turn}
          />
          {gameActive ? (
            rapping ? (
              <p className="text-white m-5 text-center">{currentVerse}</p>
            ) : (
              <TopicPrompts
                topics={[
                  "their momma",
                  "their momma and daddy and sister and cousin",
                  "their dog",
                ]}
                startVerse={startVerse}
              />
            )
          ) : (
            <></>
          )}
          <motion.button
            className="text-white text-4xl fixed bottom-16 left-1/2 -translate-x-1/2"
            onClick={startGame}
            animate={gameActive ? "hidden" : "closed"}
            variants={startBtn}
            transition={{ ease: "circIn", duration: 1 }}
          >
            Start Battle!
          </motion.button>
        </div>
      </main>
    </>
  );
}
