import Head from "next/head";
import { useState } from "react";
import Dropdown from "react-dropdown";
import "react-dropdown/style.css";

const rappers = ["Drake", "Kanye", "Future", "Young Thug"];

export default function Home() {
  const [rapper1, setRapper1] = useState<string>();
  const [rapper2, setRapper2] = useState<string>();

  const startGame = (e: any) => {
    console.log(rapper1);
    console.log(rapper2);
  };

  return (
    <>
      <Head>
        <title>Co:here to Rule the Mic!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-screen h-screen fixed bg-pixelart flex flex-col text-center items-center">
          <div className="w-full h-full bg-black opacity-80 fixed -z-10"></div>
          <h1 className="text-white text-7xl mt-12">
            Co:here to Rule the Mic!
          </h1>
          <p className="text-white text-xl mt-8 max-w-lg">
            Listen up! It's the AI Rap Battle, two digital MCs clashin' rhymes,
            algorithms and beats, in a virtual arena, no human needed. They'll
            bring the heat and show what's possible, with bars so fly it'll
            leave you speechless. Get ready for a digital showdown, it's the AI
            Rap Battle, and it's gonna be lit!
          </p>
          <div className="flex w-full justify-center gap-[500px] mt-56">
            <Dropdown
              options={rappers}
              onChange={(e) => setRapper1(e.value)}
              value={rapper1}
              placeholder="Rapper #1"
            />
            <Dropdown
              options={rappers}
              onChange={(e) => setRapper2(e.value)}
              value={rapper2}
              placeholder="Rapper #2"
            />
          </div>
          <button
            className="text-white text-4xl fixed bottom-32 left-1/2 -translate-x-1/2"
            onClick={startGame}
          >
            Start Game
          </button>
        </div>
      </main>
    </>
  );
}
